# server/src/config/application.yaml
development:
  env: "dev" # 개발 환경
  database:
    type: "memory" # 로컬 개발 환경에서는 가상 메모리 저장소 작동
  redis:
    host: "localhost"
    port: 6379

production:
  env: "prod"
  database:
    type: "mysql"
    host: ${DB_HOST:127.0.0.1}
    port: ${DB_PORT:3306}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:dhkdTlqfl0509^}
    database: ${DB_NAME:testdb}
  redis:
    host: ${REDIS_HOST:AWS_ELASTICACHE_ENDPOINT_HERE}
    port: ${REDIS_PORT:6379}