CREATE TABLE IF NOT EXISTS users (
    userId INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    nickname VARCHAR(50) NOT NULL,
    profileImage VARCHAR(500) NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    lastLoginAt TIMESTAMP NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
);

CREATE TABLE IF NOT EXISTS userState (
    userId INT PRIMARY KEY,

    totalGames INT NOT NULL DEFAULT 0,
    winCount INT NOT NULL DEFAULT 0,
    loseCount INT NOT NULL DEFAULT 0,
    drawCount INT NOT NULL DEFAULT 0,

    rating INT NOT NULL DEFAULT 1200,

    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT fk_userstate_user
    FOREIGN KEY (userId)
    REFERENCES users(userId)
    ON DELETE CASCADE
);