# Pod가 사용할 IAM 권한 연결용 ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  # iam.tf의 IRSA 설정(namespace_service_accounts)과 이름이 일치해야 함
  name: team1-backend-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::727646470302:role/team1-backend-irsa"
